services:
  # Application service
  agilizando:
    image: "webertmaximiano/agilizando-o-futuro:latest"
    environment:
      - TZ=America/Sao_Paulo
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G
      replicas: 1
    volumes:
      - ./src:/var/www/src
      - agilizando_storage:/var/www/src/storage
      - agilizando_bootstrap:/var/www/src/bootstrap
    networks:
      - agilizando

  # Web server (Nginx)
  nginx:
    image: nginx:latest
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      replicas: 1
      restart_policy:
        condition: on-failure
    
    volumes:
      - ./src:/var/www/src:ro # Código como somente leitura
      - ./docker/nginx/agilizando-production.conf:/etc/nginx/conf.d/default.conf  # Arquivo de configuração customizado do Nginx
      - agilizando_logs:/var/log/nginx  # Logs persistentes do Nginx

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`agilizando.clubesiga.com.br`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=leresolver"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

    networks:
      - web
      - agilizando

    depends_on:
      - agilizando

volumes:
  agilizando_logs:
    driver: local
  agilizando_storage:
    driver: local
  agilizando_bootstrap:
    driver: local

networks:
  web:
    external: true
  agilizando:
    driver: overlay