version: "3.8"

services:
  # --- Serviço da Aplicação (PHP-FPM) ---
  agilizando-app:
    # ✅ IMAGEM CORRETA E DINÂMICA
    image: ${APP_IMAGE_TAG:-ghcr.io/clube-siga/agilizando-app:latest}
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - .env.production
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - agilizando_storage:/var/www/html/storage
      - ./.env.production:/var/www/html/.env
    networks:
      - staging

  # --- Servidor Web (Nginx) ---
  agilizando-nginx:
    # ✅ IMAGEM CORRETA E DINÂMICA
    image: ${NGINX_IMAGE_TAG:-ghcr.io/clube-siga/agilizando-nginx:latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./docker/nginx/agilizando-production.conf:/etc/nginx/conf.d/default.conf
      - agilizando_storage:/var/www/html/storage/app/public 
      - agilizando_logs:/var/log/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agilizando-prod.rule=Host(`agilizando.clubesiga.com.br`)"
      - "traefik.http.routers.agilizando-prod.entrypoints=websecure"
      - "traefik.http.routers.agilizando-prod.tls.certresolver=leresolver"
      - "traefik.http.services.agilizando-prod.loadbalancer.server.port=80"
    networks:
      - web
      - staging
    depends_on:
      - agilizando-app

# --- Definição dos Volumes e Redes Externas ---
volumes:
  agilizando_logs:
    external: true
  agilizando_storage:
    external: true

networks:
  web:
    external: true
  staging:
    external: true