services:
  # Application service
  agilizando:
    image: "webertmaximiano/agilizando-o-futuro:latest"
    environment:
      - TZ=America/Sao_Paulo
    deploy:
      replicas: 1
    volumes:
       - ./src:/var/www/src
       - app_storage:/var/www/src/storage
       - app_bootstrap:/var/www/src/bootstrap
    networks:
      - web

  # Web server (Nginx)
  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    
    volumes:
    - ./src:/var/www/src:ro # Código como somente leitura
    - ./docker/nginx/agilizando-dev.conf:/etc/nginx/conf.d/default.conf  # Arquivo de configuração customizado do Nginx
    - app_logs:/var/log/nginx  # Logs persistentes do Nginx

    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.nginx.rule=Host(`agilizando.local.dev`)"
    - "traefik.http.routers.nginx.entrypoints=websecure"
    - "traefik.http.routers.nginx.tls.certresolver=leresolver"
    - "traefik.http.services.nginx.loadbalancer.server.port=80"

    networks:
      - web
    depends_on:
      - agilizando

  node:
    image: node:latest
    deploy:
      restart_policy:
        condition: on-failure
    working_dir: /src
    volumes:
      - ./src:/src
      - ./docker/certs/cert.pem:/certs/cert.pem
      - ./docker/certs/privkey.pem:/certs/privkey.pem
    command: npm run dev  --vite --host 0.0.0.0 --cert /certs/cert.pem --key /certs/privkey.pem

    depends_on:
      - agilizando
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`agilizando.local.dev`) && PathPrefix(`/@vite`)"
      - "traefik.http.routers.node.entrypoints=websecure"
      - "traefik.http.routers.node.tls=true"
      - "traefik.http.services.node.loadbalancer.server.port=5173"

volumes:
  app_logs:
    driver: local
  app_storage:
    driver: local
  app_bootstrap:
    driver: local

networks:
  web:
    external: true