version: "3.8"
# --- ✅ PASSO 1: Declaração de que os segredos já existem no Swarm ---
secrets:
  app_key_agilizando:
    external: true
  app_agilizando_db: 
    external: true
  db_username:
    external: true
  db_password:
    external: true

services:
  # --- Serviço da Aplicação (PHP-FPM) ---
  agilizando-app:
    image: ${APP_IMAGE_TAG:-ghcr.io/clube-siga/agilizando-app:latest}
    environment:
      - TZ=America/Sao_Paulo
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
    env_file: [".env.production"]
    user: "82"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - agilizando_storage:/var/www/app/storage

    networks:
      - staging
    # --- ✅ PASSO 2: Adiciona os segredos ---
    secrets:
      - app_key_agilizando
      - app_agilizando_db
      - db_username
      - db_password

    #command: php-fpm

  # --- Servidor Web (Nginx) ---
  agilizando-nginx:
    # ✅ IMAGEM CORRETA E DINÂMICA
    image: ${NGINX_IMAGE_TAG:-ghcr.io/clube-siga/agilizando-nginx:latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./docker/nginx/agilizando-production.conf:/etc/nginx/conf.d/default.conf
      - agilizando_storage:/var/www/app/storage:ro
      - agilizando_logs:/var/log/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agilizando-nginx.rule=Host(`agilizando.clubesiga.com.br`)"
      - "traefik.http.routers.agilizando-nginx.entrypoints=websecure"
      - "traefik.http.routers.agilizando-nginx.tls.certresolver=leresolver"
      - "traefik.http.services.agilizando-nginx.loadbalancer.server.port=80"
    networks:
      - web
      - staging
    depends_on:
      - agilizando-app

  # --- Worker para Filas (Queues) ---
  agilizando-worker:
    image: ${APP_IMAGE_TAG:-ghcr.io/clube-siga/agilizando-app:latest}
    command: "php artisan queue:work --sleep=3 --tries=3"
    user: "82"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - staging
    environment:
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    secrets:
      - app_key_agilizando
      - app_agilizando_db
      - db_username
      - db_password

# --- Definição dos Volumes e Redes Externas ---
volumes:
  agilizando_logs:
    external: true
  agilizando_storage:
    external: true

networks:
  web:
    external: true
  staging:
    external: true
