services:
    agilizando:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - web-local # Mantém a rede para comunicação interna se necessário
        # Removidas as labels do Traefik e portas, pois o Nginx será o ponto de entrada

    nginx: # Novo serviço Nginx
        image: nginx:stable-alpine
        ports:
            - '${APP_PORT:-80}:80' # Expor a porta 80 para o Traefik
            - '${VITE_PORT:-5173}:5173' # Expor a porta 5173 para o Vite HMR (se usado)
        volumes:
            - '.:/var/www/html' # Montar o projeto para o Nginx
            - '../docker/nginx/agilizando-dev-sail.conf:/etc/nginx/conf.d/default.conf:ro' # Montar sua nova config Nginx
        networks:
            - web-local # Conectar à rede do Traefik
        depends_on:
            - agilizando # Nginx depende do serviço Laravel
        labels: # Labels do Traefik para o serviço Nginx
            - "traefik.enable=true"
            - "traefik.http.routers.agilizando.rule=Host(`agilizando.local.dev`)"
            - "traefik.http.routers.agilizando.entrypoints=websecure"
            - "traefik.http.routers.agilizando.tls=true"
            - "traefik.http.services.agilizando.loadbalancer.server.port=80" # Nginx escuta na porta 80
            - "traefik.docker.network=web-local"

networks:
    sail:
        driver: bridge
    web-local:
        external: true
volumes:
    sail-mysql:
        driver: local
