services:
    agilizando:
        image: php:8.4-fpm-alpine
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - web-local
        # Removidas as labels do Traefik e portas, pois o Nginx será o ponto de entrada

    nginx:
        image: nginx:stable-alpine
        volumes:
            - '.:/var/www/html'
            - '../docker/nginx/agilizando-dev.conf:/etc/nginx/conf.d/default.conf:ro'
        networks:
            - sail
            - web-local
        depends_on:
            - agilizando
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.agilizando.rule=Host(`agilizando.local.dev`)"
            - "traefik.http.routers.agilizando.entrypoints=websecure"
            - "traefik.http.routers.agilizando.tls=true"
            - "traefik.http.services.agilizando.loadbalancer.server.port=80"
            - "traefik.docker.network=web-local"

networks:
    sail:
        driver: bridge
    web-local:
        external: true
volumes:
    sail-mysql:
        driver: local
