name: Deploy Site Agilizando  SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: github_actions_deploy_key
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: overwrite

    - name: Sync files with rsync
      run: |
        rsync -avz -e "ssh -i ~/.ssh/github_actions_deploy_key -o StrictHostKeyChecking=no -p 6781" \
        --exclude '*.env*'  ./ webert@31.97.90.215:/home/webert/agilizando.clubesiga.com.br/

    - name: SSH to VPS and deploy
      run: |
        ssh -t -i -i ~/.ssh/github_actions_deploy_key -o StrictHostKeyChecking=no -p 6781 webert@31.97.90.215 << 'EOF'
          cd /home/webert/agilizando.clubesiga.com.br
          docker stack deploy -c docker-swarm-prod.yml agilizando
        EOF
