# main.yml

name: CI/CD - Build e Deploy para Agilizando - Main

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME_APP: ghcr.io/clube-siga/agilizando-app
  IMAGE_NAME_NGINX: ghcr.io/clube-siga/agilizando-nginx

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login no GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push App (PHP-FPM) Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        target: final
        tags: |
          ${{ env.IMAGE_NAME_APP }}:latest
          ${{ env.IMAGE_NAME_APP }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and Push Nginx Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        target: nginx_production
        tags: |
          ${{ env.IMAGE_NAME_NGINX }}:latest
          ${{ env.IMAGE_NAME_NGINX }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    name: Deploy para o Servidor
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Adicionar Chave do Host da VPS ao known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p 6781 31.97.90.215 >> ~/.ssh/known_hosts

    - name: Instalar chave SSH para acesso ao servidor
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: github_actions_deploy_key
        known_hosts: 'useless' # A chave já foi adicionada pelo passo anterior

    - name: Fazer Deploy da Stack no Servidor
      run: |
        export APP_IMAGE_TAG="${{ env.IMAGE_NAME_APP }}:${{ github.sha }}"
        export NGINX_IMAGE_TAG="${{ env.IMAGE_NAME_NGINX }}:${{ github.sha }}"
        
        echo "Deploy da imagem da App: $APP_IMAGE_TAG"
        echo "Deploy da imagem do Nginx: $NGINX_IMAGE_TAG"

        ssh -A -i ~/.ssh/github_actions_deploy_key -o StrictHostKeyChecking=no -p 6781 webert@31.97.90.215 "
          set -e
          echo '--> Sincronizando arquivos de configuração via Git...'
          cd /home/webert/agilizando.clubesiga.com.br

          # O Agente SSH está sendo encaminhado (flag -A), então não é necessário iniciar um novo.
          git fetch origin main
          git reset --hard origin/main
          
          # ✅ CORREÇÃO DE SEGURANÇA: Removemos o 'x' para não apagar arquivos em .gitignore,
          # como o seu essencial .env.production.
          git clean -df

          echo '--> Fazendo login no GitHub Container Registry...'
          echo '${{ secrets.GHCR_PAT }}' | docker login ghcr.io -u '${{ github.actor }}' --password-stdin
          
          echo '--> Fazendo deploy da stack Docker com as imagens atualizadas...'
          APP_IMAGE_TAG=${APP_IMAGE_TAG} \
          NGINX_IMAGE_TAG=${NGINX_IMAGE_TAG} \
          docker stack deploy -c docker-swarm-prod.yml agilizando --with-registry-auth

          echo '--> Deploy finalizado com sucesso!'
        "
