# staging.yml

name: CI/CD - Build e Deploy para Agilizando - Main

on:
  push:
    branches:
      - main

env:
  # Nome da imagem da aplicação PHP-FPM
  IMAGE_NAME_APP: ghcr.io/${{ github.repository_owner }}/agilizando-app
  # Nome da imagem do Nginx
  IMAGE_NAME_NGINX: ghcr.io/${{ github.repository_owner }}/agilizando-nginx

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Passo para construir e publicar a imagem da APLICAÇÃO
    - name: Build and Push App Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        # Constrói apenas o estágio "final" (PHP-FPM)
        target: final
        tags: |
          ${{ env.IMAGE_NAME_APP }}:agilizando
          ${{ env.IMAGE_NAME_APP }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Passo para construir e publicar a imagem do NGINX
    - name: Build and Push Nginx Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        # Constrói apenas o estágio "nginx_production"
        target: nginx_production
        tags: |
          ${{ env.IMAGE_NAME_NGINX }}:agilizando
          ${{ env.IMAGE_NAME_NGINX }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Staging VPS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY}}
        name: github_actions_deploy_key
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Sync Swarm file to VPS
      run: |
        rsync -avz -e "ssh -i ~/.ssh/github_actions_deploy_key -o StrictHostKeyChecking=no -p 6781" \
        ./docker-swarm-prod.yml webert@31.97.90.215:/home/webert/agilizando.clubesiga.com.br/docker-swarm-prod.yml

    - name: Deploy to Agilizando - Main 
      run: |
        export APP_IMAGE_TAG="${{ env.IMAGE_NAME_APP }}:${{ github.sha }}"
        export NGINX_IMAGE_TAG="${{ env.IMAGE_NAME_NGINX }}:${{ github.sha }}"
        
        echo "Deploying App Image: $APP_IMAGE_TAG"
        echo "Deploying Nginx Image: $NGINX_IMAGE_TAG"

        ssh -i ~/.ssh/github_actions_deploy_key -o StrictHostKeyChecking=no -p 6781 webert@31.97.90.215 "
          set -e
          echo '--> Logging in to GitHub Container Registry...'
          echo '${{ secrets.GHCR_PAT }}' | docker login ghcr.io -u '${{ github.actor }}' --password-stdin
          
          cd /home/webert/agilizando.clubesiga.com.br
          
          echo '--> Deploying Docker stack with updated images...'
          
          # A variável do secret FOI REMOVIDA daqui. Não é mais necessária.
          APP_IMAGE_TAG=${APP_IMAGE_TAG} \
          APP_IMAGE_NGINX_TAG=${NGINX_IMAGE_TAG} \
          docker stack deploy -c docker-swarm-prod.yml agilizando --with-registry-auth

          echo '--> Deploy finished successfully!'
        "
